Add support for services and improve memory managment and error handling
ros2-dotnet/ros2_dotnet pull request #90
Opened 2021-11-12 13:18 UTC by hoffmann-stefan

Will post more details later on. This is based on the previous PR #89.

It is complete as far as I'm concerned, but opened as draft as it is waiting for the collections PR.

2021-11-12 17:26 UTC, esteve commented
@hoffmann-stefan thanks! I prefer this PR much more than the one submitted by @ooeygui / Microsoft since it's more focused and doesn't change the license. Let me know when it's ready for review and I'll do it.

2021-11-15 13:28 UTC, hoffmann-stefan commented
@esteve: I updted the PR description with more details. If youre done reviewing the other PR without major issues you can continue with this one. I don't plan on adding more code in this PR except to address something from a review.

2022-01-24 11:20 UTC, esteve commented
@hoffmann-stefan sorry for the late response, I was hoping we could get #86 fixed soon, but then holiday season and covid struck. Overall, changes look good to me, but I'd like to get the CI fixed as soon as possible so we can properly test this PR and the other one you submitted.

Would your team be interested in helping with the CI issues? There seems to be a conflict with newer versions of ROS GitHub action and ros2-dotnet.

2022-01-26 08:08 UTC, hoffmann-stefan commented
> @hoffmann-stefan sorry for the late response, I was hoping we could get #86 fixed soon, but then holiday season and covid struck.

@esteve No worries, thanks for looking at the PRs. Seems like #86 got some progress by @ooeygui since you wrote this comment. In the short term we need to hold some deadlines so we don't realy have time to look into something new. Most of the team uses linux and the other ones (like me) use [WSL2](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) so no one has a working Windows ROS setup or experience right now (seems like the windows side of the CI has problems as far as I looked). So I can't promise something right now.

2022-04-19 17:15 UTC, hoffmann-stefan commented
Rebased on top of master.
@esteve or @ooeygui: Could you please press the button to run CI? Or do you first want to get #89 green?

2022-09-12 06:25 UTC, tank104 commented
I would really like to be able to use Services, do you think this PR will get in soon?

2022-09-13 13:47 UTC, hoffmann-stefan commented
@tank104:

I [pinged the maintainers](https://github.com/ros2-dotnet/ros2_dotnet/pull/89#issuecomment-1120847977) back in may about the review of the PRs, but no word yet.

To use these features you don't need the PRs to be merged though, you can checkout the branch from the PR and use that one instead in your workspace. In doing so you could give feedback if this worked for you and maybe start a review of the PRs to help get them merged.

2022-09-13 13:55 UTC, esteve commented
@hoffmann-stefan

> I [pinged the maintainers](https://github.com/ros2-dotnet/ros2_dotnet/pull/89#issuecomment-1120847977) back in may about the review of the PRs, but no word yet.

I'm really sorry, I completely missed your message. I'll have a look at it and #89 now, but to be honest, I'll most likely just merge it, the changes look fine overall

2022-11-10 14:08 UTC, esteve requested changes

2022-11-10 14:16 UTC, esteve commented
Changes look fine overall, only one change request.

@ooeygui I like this PR because it's self contained. Thanks for the work done in the other services PR. If you're ok with this PR, once the change request is addressed, we can merge it. Can you have a look at it? Thanks.

2022-11-14 18:00 UTC, hoffmann-stefan commented on NOTICE
> +Stefan Hoffmann (stefan.hoffmann@schiller.de)
Didn't know about the implications of changching this file.
Did some quick googling and found this if others wonder as well: https://infra.apache.org/licensing-howto.html

Removed the change and pushed again.

2022-11-14 18:01 UTC, hoffmann-stefan commented
Rebased on top of master and adressed @esteve's change request

2023-03-05 20:07 UTC, hoffmann-stefan commented
Found the issue with CI

- There was a break in `ament_core` that was caused by CMake 3.24.
  - https://github.com/ament/ament_cmake/pull/395
- The github action windows runner images updated to newer CMake version, but the binaries used in CI didn't include the fix from the PR to ament_cmake above
- I created a PR to `setup_ros` that updates the windows binary releases to include the fix: https://github.com/ros-tooling/setup-ros/pull/548

Once the PR to `setup_ros` is merged and tagged we can use this here. Will update and clean up this PR then, maybe even first creating a PR that fixes CI and then rebasing this PR.

2023-03-14 07:37 UTC, hoffmann-stefan commented
@esteve:

Took some time, but now your change request is resolved and CI is fixed again, mostly due to find the time to debug windows CI.

Here are the changes since your last review (see the small notices about force pushes to this PR): https://github.com/ros2-dotnet/ros2_dotnet/compare/79a338d8c04e8240e651dd31b274bfa75aa8d15b..2068e8b0d2b055cfe4051b26d450508524ef940d

Created a separate PR for testing the CI fixes on master, this PR is now rebased on top of it: https://github.com/ros2-dotnet/ros2_dotnet/pull/96

Could you take a look again and approve/merge if it's OK? (maybe #96 or directly this one as it includes the one commit)

Before merging please notice the comment over at https://github.com/ros2-dotnet/ros2_dotnet/pull/89#issuecomment-1314146430 to not loose the logical commits for this PR by an accidental squash merge (if there is a reason for squash merge I am fine with it too).

2023-04-22 06:31 UTC, merged